Notifiarr/notifiarr

pkg/client/plexsnaps.go, pkg/client/tray_commands.go, pkg/notifiarr/notifiarr.go, pkg/notifiarr/plexcron.go, pkg/notifiarr/snapcron.go, pkg/plex/sessions.go, pkg/services/services.go
This moves all the prints for debug payloads to 1 place. Adds a new GetSessions method too.
=> Print debug payloads from 1 place.

scripts/install-synology.sh
This needs to be tested. This script should be safe to re-run over and over. It will just update the binary and init file. Closes #39.
To test this from this branch/PR:
```bash
```
---
Delete the existing notifiarr user to make sure the script correctly adds the new one. You can also delete the shudders entry and init file for a full test. Run it again to make sure it doesn't have any weird errors on a second pass.
=> Add user to synology in script.

go.mod, go.sum, pkg/apps/apps.go, pkg/apps/lidarr.go, pkg/apps/radarr.go, pkg/apps/readarr.go, pkg/apps/sonarr.go, pkg/client/handlers.go, pkg/client/plexsnaps.go, pkg/client/start.go, pkg/client/webserver.go, pkg/logs/cooler.go, pkg/notifiarr/plexcron.go, scripts/install-synology.sh
This contribution:
- Fixes config file access on a Synology.
- Removes the cool down from all media types except resume and pause. Closes #49.
- Allows the incoming pix web hook to use the API Key OR the Plex Token. Previously it only worked with the Plex Token, now you can use either string to authorize Plex to post to this app.
- Hides the Plex Token and Notifiarr API Key from logs.
- Adds search trigger ability for all four Starr apps.
=> Syno fix, cool down fix, token advancement.

pkg/client/start.go, pkg/configfile/template.go, pkg/services/check_proc.go
Fixed:
- Special characters were breaking parts of the config template. Preserve those with single quotes.
- Some PIDs (administrator tasks) were missing from Windows process list (`--ps` and process service check).
=> Find missing windows PIDs. Fix config template for special characters.

scripts/install-synology.sh
This adds code to the Synology install script so it can be run in crontab to keep notifiarr up to date. Closes #50.
Test like this (**as root**).
```
curl -sSL https://github.com/Notifiarr/notifiarr/releases/download/v0.1.2/notifiarr.amd64.linux.gz | gunzip > /usr/bin/notifiarr
curl -sSL https://raw.githubusercontent.com/Notifiarr/notifiarr/dn2_syno_auto_update/scripts/install-synology.sh | bash
```
=> Make synology install script upgrade-aware

README.md, pkg/bindata/generate.go, pkg/configfile/template.go, pkg/logs/logs.go, pkg/services/services.go
This contribution adds a log file for service checks. They're spammy and this allows getting them out of the app log. Closes #75.
Debug POST logs still hit the app log, but this is better than it was.
=> Add log file for services checks.

go.mod, pkg/client/init.go, pkg/client/start.go, pkg/client/tray.go, pkg/notifiarr/cfsync.go, pkg/notifiarr/notifiarr.go, pkg/notifiarr/timers.go, pkg/plex/sessions.go
This enables Sonarr Quality Profiles sync. Require @austinwbest to make some changes on the website, and depends on  https://github.com/TRaSH-/Guides/pull/280.
- Also fixes a crashing bug with windows + no debug.
- And bubbles up the response body from Plex when a sessions GET returns a non-200.
- Fixes the ability to unmonitor a movie. https://github.com/golift/starr/commit/9d240026989c59a6b38d1a8d21edb97c892fd755
=> Make sonarr quality releases palpable.

go.mod, go.sum, pkg/apps/apps.go, pkg/apps/sonarr.go
Closes #85.
- Adds `GET /getEpisodes/{seriesid:[0-9]+}` - Returns a list of [episodes](https://github.com/golift/starr/blob/040e53eb75d015f59b40b1cd3cb0dbe595c006b9/sonarr/type.go#L182-L197) in the `message`.
- Adds `GET /unmonitor/{episodeid:[0-9]+}` - Returns a single [episode](https://github.com/golift/starr/blob/040e53eb75d015f59b40b1cd3cb0dbe595c006b9/sonarr/type.go#L182-L197) in the `message`.
Relies on library updates: https://github.com/golift/starr/commit/040e53eb75d015f59b40b1cd3cb0dbe595c006b9
=> Add two new sonarr methods.

go.mod, go.sum, pkg/apps/lidarr.go, pkg/apps/radarr.go, pkg/apps/readarr.go, pkg/apps/sonarr.go, pkg/client/tray.go, pkg/configfile/template.go, pkg/notifiarr/stuckitems.go, pkg/notifiarr/timers.go
Closes #86. Adds a five minute ticker to check the queue on every app. Looks for completed items, or items with an error message. Sends them all in one POST to notifiarr.com. The content is the entire queue item record. I can trim it down, but this was quick and easy. Adds a couple new menu items, and a config item for each app to enable the new notification feature. I also disabled the dev and test endpoints when debug is false (menu cleanup/shrinkage).
TODO: readme update
```
[DEBUG] 2021/06/25 03:34:22 Checking Lidarr (1) Queue for Stuck Items, queue size: 1, stuck: 1
[DEBUG] 2021/06/25 03:34:22 Checking Radarr (1) Queue for Stuck Items, queue size: 3, stuck: 3
[DEBUG] 2021/06/25 03:34:22 Checking Readarr (1) Queue for Stuck Items, queue size: 0, stuck: 0
[DEBUG] 2021/06/25 03:34:22 …
```
=> Add stuck queue items check for all Starr apps.

examples/notifiarr.conf.example, pkg/apps/apps.go, pkg/client/handlers.go, pkg/client/tray.go, pkg/client/tray_commands.go, pkg/client/webserver.go, pkg/configfile/config.go, pkg/configfile/template.go, pkg/logs/logs_linux.go, pkg/logs/logs_others.go, pkg/logs/logs_windows.go
Updates the bind_addr description in the config file. Closes #95. 
Fixes a crashing bug on windows. Closes #94. 
Fixes a crashing bug when Plex is down/unreachable. Closes #98.
Make the `urlbase` (setting) path return a 200 instead of 404. Repotted by @RumlePot
Changes error/panic logging a bit more.
=> Update template.go and fix some bugs.

pkg/client/handlers.go, pkg/client/tray.go, pkg/notifiarr/notifiarr.go, pkg/notifiarr/plexcron.go, pkg/notifiarr/snapcron.go, pkg/notifiarr/state.go, pkg/notifiarr/stuckitems.go, pkg/notifiarr/timers.go, pkg/services/services.go
This adds incoming triggers for:
- services
- dashboard
- snapshot
- sessions
- stuck items
Moves several of these external requests into the native go routine for the ticker running each item. This is accomplished by adding a new channel to send the request to. Closes #103.
=> Add incoming API triggers, channelize calls

pkg/client/handlers.go, pkg/client/start.go, pkg/configfile/flags.go, pkg/notifiarr/clientinfo.go, pkg/notifiarr/notifiarr.go
This adds some startup data so we can track usage (version) statistics; closes #105. Re-used the `version` API endpoint code and made both implementations use the same data. Moved the ClientInfo code for incoming and outgoing info into one file. Also moved Flags into the `configfile` package.
=> Move flags to configfile, and add startup info post

pkg/apps/sonarr.go
This satisfies the client-needed portion of the request in https://github.com/Notifiarr/website/issues/51.
Works just like the existing `trigger/search/id` endpoint, except it's `trigger/refresh/id`. It's also dynamic, so you can send other `SeriesXX` commands.
=> Add sonarr refresh endpoint

README.md, examples/notifiarr.conf.example, go.mod, go.sum, pkg/client/cli.go, pkg/client/init.go, pkg/client/start.go, pkg/configfile/config.go, pkg/configfile/template.go, pkg/mnd/constants.go, pkg/notifiarr/snapcron.go, pkg/services/apps.go, pkg/services/check_proc.go, pkg/services/check_proc_pre.go, pkg/services/checks.go, pkg/services/config.go, pkg/snapshot/diskio.go, pkg/snapshot/diskusage.go, pkg/snapshot/mysql.go, pkg/snapshot/snapshot.go, pkg/snapshot/system.go, pkg/update/check.go
So far this adds `iostat` and `iotop` data collection to snapshots for Linux (non-Docker). Also adds "top" (top cpu-using processes), and  includes CPU times for most platforms.  This explains the CPU times data: https://github.com/shirou/gopsutil/blob/fb65e185a90cc6aff00678664869701d491d9a43/v3/cpu/cpu.go#L16-L30
snapshot config payload has two new items: `psTop` and `ioTop`, both integers representing how many processes to return.
`iotop` requires `sudo`. example, make sure to get the path correct:
```
notifiarr ALL=(root) NOPASSWD:/usr/sbin/iotop *
```
Also added mysql "top process list" to snapshots.
=> Snapshot improvements.

LICENSE, README.md, examples/MANUAL.md, go.mod, go.sum, pkg/apps/lidarr.go, pkg/apps/radarr.go, pkg/apps/readarr.go, pkg/apps/sonarr.go, pkg/notifiarr/clientinfo.go, pkg/services/interface.go, pkg/services/services.go, pkg/snapshot/mysql.go
- Allows sonarr commands to work from the website (fixes TBA/refreshseries).
- Minor REDME updates because @bakerboy448 is dyslexic.
- Service check updates are now sent even if no services are present.
- URLs that are correct no longer generate startup warnings.
- Random hostnames generated by Kubernetes on TrueNAS are fixed.
- Other Kube uses will still not work well.
- Library updates.
=> Fix sonarr commands, other minor fixes.

pkg/apps/apps.go, pkg/apps/downloaders.go, pkg/apps/lidarr.go, pkg/apps/radarr.go, pkg/apps/readarr.go, pkg/apps/sonarr.go
Closes #133 by fixing the bug. An error is now returned when an invalid configuration is provided.
=> Fixes a bug.

pkg/snapshot/snapshot.go, pkg/snapshot/synology.go
Fixes a bug.
```
[INFO] 2021/12/22 12:21:15 [cron requested] Gathering and sending System Snapshot.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x7af2f5]
goroutine 71 [running]:
github.com/Notifiarr/notifiarr/pkg/snapshot.(*Synology).SetInfo(...)
github.com/Notifiarr/notifiarr/pkg/snapshot/synology.go:79
github.com/Notifiarr/notifiarr/pkg/snapshot.(*Config).getSnapshot(0xc00054e0a0, {0xa0a228, 0xc01a816960}, 0xc01a836280)
github.com/Notifiarr/notifiarr/pkg/snapshot/snapshot.go:163 +0x315
github.com/Notifiarr/notifiarr/pkg/snapshot.(*Config).GetSnapshot(0xc00054e0a0)
github.com/Notifiarr/notifiarr/pkg/snapshot/snapshot.go:147 +0x145
github.com/Notifiarr/notifiarr/pkg/notifiarr.(*Config).sendSnapshot(0x …
```
=> fix bug causing crash in snapshot

pkg/client/cli.go, pkg/configfile/config.go, pkg/plex/plex.go, pkg/services/apps.go
Deluge service checks are returning a 405 Method Not Allowed. This fixes it. Confirmed twice.
Added two more fixes:
1. Do not overwrite files with config writing feature. Closes #151.
2. Strip slashes off the end of the Plex URL.
=> fix deluge service check bug, and other bugs.

go.mod, go.sum, pkg/notifiarr/backups.go
This contribution adds a new feature that allows Notifiarr client to download backup files from starr apps. It then extracts those files, and checks the sqlite database file for corruption. Corrupt databases trigger notifications in your Discord. Closes #142. Also closes #148. Closes #155 by adding `-e` flag and formatting durations in two other libraries: https://github.com/golift/starr/pull/23, https://github.com/golift/cnfg/commit/ad131bdf6bbc936c2c4647e3c3cb715d7ebc70f1, plus a few changes locally.
This also adds prowler support. Service checks and corruption check at this point. It has no API methods.
Requires https://github.com/golift/starr/pull/17 and https://github.com/golift/starr/pull/22
=> Add starr app database backup corruption check.

examples/compose.yml
Adds a basic docker-compose template for the notifiarr client.
This foregoes more advanced options such as SYS_RAWIO capabilities or passing through of devices for smart monitoring.
=> Compose template

Makefile, pkg/notifiarr/clientinfo.go, pkg/notifiarr/handlers.go
- Use go routines to get app versions in parallel.
- Increase golangci-lint timeout. Caused 0.2.5 to fail building.
- Add Tautulli count in missing startup payload.
=> Makes version endpoint faster.

pkg/configfile/template.go, pkg/notifiarr/notifiarr.go, pkg/notifiarr/timers.go, pkg/notifiarr/website.go
This switches custom cron timers from GET to POST so they contain host info.
=> Switch custom cron timers to POST.

pkg/client/start.go, pkg/configfile/config.go
Starr app checks happen on every invocation of the client, even -version. This fixes that by moving the starr app setup to after the startup flags are checked.
=> Move Starr checks after flag checks.

pkg/client/client_other.go, pkg/client/handlers_plex.go, pkg/client/tray.go, pkg/logs/share/share.go, pkg/services/interface.go, pkg/services/services.go, pkg/triggers/backups/backups.go, pkg/triggers/backups/corruption.go, pkg/triggers/cfsync/radarr.go, pkg/triggers/cfsync/sonarr.go, pkg/triggers/common/triggers.go, pkg/triggers/crontimer/custom.go, pkg/triggers/dashboard/dashboard.go, pkg/triggers/filewatch/filewatch.go, pkg/triggers/gaps/gaps.go, pkg/triggers/plexcron/meta.go, pkg/triggers/plexcron/plexcron.go, pkg/triggers/snapcron/snapcron.go, pkg/triggers/stuckitems/stuckitems.go, pkg/triggers/triggers.go, pkg/website/clientinfo.go, pkg/website/server.go, pkg/website/website.go, pkg/website/website_routes.go
This moves the send data function to use a channel. All requests to the website are now handled in a single go routine.
=> Channelize all website comms

pkg/client/start.go, pkg/snapshot/raid.go, pkg/snapshot/snapshot.go
Closes #226 by exposing all the virtual disks to the website. Also fixes snapshots that were broken in a previous commit.
=> Adds support for multiple megaraid virtual disks.

pkg/bindata/files/css/style.css, pkg/bindata/files/js/golists.js, pkg/bindata/templates/commands.html, pkg/bindata/templates/downloaders-rtorrent.html, pkg/bindata/templates/downloaders.html, pkg/bindata/templates/filewatcher.html, pkg/bindata/templates/media.html, pkg/bindata/templates/services.html, pkg/bindata/templates/snapshot-mysql.html, pkg/bindata/templates/starr.html, pkg/client/handlers_trash.go, pkg/client/handlers_version.go, pkg/client/html_templates.go, pkg/plex/plex.go, pkg/services/apps.go, pkg/triggers/backups/backups.go, pkg/triggers/backups/config.go, pkg/triggers/backups/corruption.go, pkg/triggers/cfsync/common.go, pkg/triggers/cfsync/radarr.go, pkg/triggers/cfsync/sonarr.go, pkg/triggers/dashboard/dashboard.go, pkg/triggers/dashboard/nzbget.go, pkg/triggers/dashboard/rtorrent.go, pkg/triggers/gaps/gaps.go, pkg/triggers/stuckitems/stuckitems.go
Closes #243. This allows an instance (starr, downloads, etc) to be disabled by setting the timeout to 'Disabled' in UI (or `-1s` in config file). This also adds selectors to all the timeouts instead of raw text input.
=> Allow disabling instances.

pkg/client/start.go, pkg/logs/logs.go, pkg/services/apps.go, pkg/services/interface.go, pkg/triggers/filewatch/filewatch.go
Closes #287 by fixing a crash when collecting apps for service checks.
This also adds a limiter to the file watcher, so it won't kill itself when the file it's watching becomes unruly.
=> Fix crash when collecting apps for service checks.

pkg/triggers/filewatch/filewatch.go, pkg/triggers/filewatch/logger.go
Fixes the rate limiter on the file watcher. It was happening before the matches were checked, which was making it ignore lines it shouldn't have. Also adds a custom logger to the tail module.
=> fix rate limiter on file wtcher, add custom logger

pkg/apps/apppkg/tautulli/tautulli.go, pkg/apps/radarr.go, pkg/apps/sonarr.go, pkg/client/handlers.go, pkg/client/handlers_gui.go, pkg/configfile/config.go, pkg/triggers/cfsync/common.go, pkg/triggers/cfsync/radarr.go, pkg/triggers/cfsync/sonarr.go, pkg/triggers/common/triggers.go, pkg/triggers/data/store.go, pkg/triggers/handler.go, pkg/triggers/triggers.go
Closes #309.
- Adds five delete methods to clear out all custom formats, quality profiles and release profiles in sonarr and radarr.
- `/api/sonarr/1/customFormats/all`
- `/api/sonarr/1/qualityProfiles/all`
- `/api/sonarr/1/releaseProfiles/all`
- `/api/radarr/1/customFormats/all`
- `/api/radarr/1/qualityProfiles/all`
- Adds per-instance trash sync triggers:
- `/api/triggers/cfsync/1`
- `/api/triggers/rpsync/1`
=> TRaSH sync updated

pkg/configfile/template.go
Closes #321. Cannot use `toml.NewEncoder` on a `string`, so this is the best I can come up with.
=> protect triple ticks in commands

pkg/client/handlers_gui.go, pkg/client/handlers_websocket.go, pkg/client/html_templates.go, pkg/configfile/helper.go
Closes #270.
Keeps 10 config file backups, deletes oldest first.  Stores them in a `backup/` folder.
=> Add config file backup cleanup and put them in sub folder

README.md, examples/notifiarr.conf.example, pkg/client/handlers_gui.go, pkg/client/init.go, pkg/client/start.go, pkg/client/webserver.go, pkg/configfile/config.go, pkg/configfile/password.go, pkg/configfile/template.go
- This change allows changing the auth proxy header from the default of `x-webauth-user`. 
- You do this by changing the value of `ui_password` to `webauth:<header>` 
- e.g. `webauth:x-webauth-user` or `webauth:remote-user`
- Closes #401
- This also fixes the bug preventing `DN_UI_PASSWORD` from working as environment variable.
- You can now pass things like these from env vars, and it will work. 
```
DN_UI_PASSWORD=webauth
DN_UI_PASSWORD=webauth:remote-user
DN_UI_PASSWORD=noauth
DN_UI_PASSWORD=mySuperCoolPassw0rd
```
- Fixes #416
=> Allow changing auth header. Allow passing ui_password from env variable.

pkg/apps/api.go, pkg/client/html_templates.go, pkg/mnd/functions.go, pkg/mnd/variables.go, pkg/website/clientinfo/handlers.go, pkg/website/server.go, pkg/website/website.go, pkg/website/website_routes.go
Adds byte counters to most log lines. Adds API GET debug logs (only non-GET were being logged previously). Adds logging for errors generated during `/api/version` requests. Closes #446.
=> Logs improvements

pkg/client/cli.go, pkg/client/handlers_gui.go
- Makes `--reset` clean SSL cert and key files.
- Fixes bug preventing removing ssl cert and key in UI.
- Closes #579
=> Allow resetting ssl cert and key files

pkg/triggers/starrqueue/downloads.go, pkg/triggers/starrqueue/setup.go
Active queue is always enabled but website throws a 400 for the 1 request the client makes on startup. This disables the active queue timer if the user is not a patron.
This also adds a limit to the number of items sent in the active download payload.
=> Limit count, disable active queue for non-patron.

pkg/client/handlers_plex.go, pkg/triggers/plexcron/plexcron.go
Needed to keep scrabble at feature parity with finished items tracker.
=> Add snapshot to all plex webhooks

pkg/snapshot/mysql.go
Mariadb has 1 extra column to account for in the process list output. This makes it work.
=> Add mariadb support

go.mod, go.sum, pkg/bindata/templates/services.html, pkg/client/html_templates.go, pkg/services/apps.go, pkg/services/checks.go, pkg/triggers/plexcron/sessions.go
This adds the ability to add headers to http service checks. That change allows hiding the Plex token from errors.
- Checks some boxes on #601
=> header support for http services checks

pkg/services/apps.go, pkg/services/checks.go, pkg/services/config.go, pkg/services/interface.go, pkg/services/services.go
This adds tags to service checks that are passed to the website as metadata. The first tag is the Plex server name. Later we'll add more tag metadata.
- Closes #698
=> Add Plex name to service checks, and service check tags.

pkg/services/checks.go
HTTP service checks start out unknown, then get set to OK if we get a valid status code. They get set to critical if we get an invalid status code. They never get set to critical if the request fails. This contribution changes that behavior so a failed request will now make the service critical.
- Closes #697
=> make http service checks go critical on errors

.golangci.yml, pkg/client/handlers_gui.go, pkg/logs/logs.go, pkg/snapshot/mysql.go, pkg/snapshot/nvidia.go, pkg/snapshot/snapshot.go, pkg/triggers/autoupdate/autoupdate.go, pkg/update/cleanup.go, pkg/update/update.go
- Closes #776 
- Improves updater logs.
- Deletes all old backups except most recent 3.
- Adds `musttag` linter.
- Stop sending mysql auth info to website. (oops)
- Fix bug removing nvidia-smi path using WebUI.
- Return LookPath error when nvidia-smi cannot be found.
=> add backup cleanup codez

pkg/update/update.go
I made the updater work with unstable builds and managed to break it for regular builds. This fixes it.
- Closes #791
=> fix github updater

pkg/bindata/templates/config.html, pkg/bindata/templates/triggers.html, pkg/checkapp/commands.go, pkg/client/cli.go, pkg/client/handlers.go, pkg/client/handlers_gui.go, pkg/client/handlers_plex.go, pkg/client/html_templates.go, pkg/client/init.go, pkg/client/start.go, pkg/client/tunnel.go, pkg/configfile/config.go, pkg/services/config.go, pkg/services/interface.go, pkg/services/services.go, pkg/triggers/common/triggers.go, pkg/triggers/crontimer/custom.go, pkg/triggers/handler.go, pkg/triggers/triggers.go
Code refactor around how config data is stored. We now store a copy of the original config before modifying it with validators and filepath parsers. This allows us to determine if the HostID is saved or not.
- Stores copy of input config internally.
- Applies this new data copy to UI 'string' input elements on config UI page.
- Applies home dir (`~`) support to `filepath:` inputs.
- Prints filepath input files and variable names on start/reload.
- Save button now appears in UI when host ID is not saved. 
- Closes #796
=> Save config input for later use

pkg/client/start.go
When installing a new client on Windows or macOS the app traditionally opens the config file so the user can add their API key. Instead, we now throw a pop-up that asks for the API key.
=> ask for key instead of open config file

frontend/src/includes/InstancesTab.svelte, frontend/src/pages/downloadApps/Index.svelte, frontend/src/pages/fileWatcher/Index.svelte, frontend/src/pages/starrApps/Index.svelte
Back button was mostly working. Thought it was worse than it was. I only found that tabs on Starr and Downloaders pages didn't work with the back button. This fixes the problem by calling `setTab` on `popState`.
Also made a change to only show the `Match:` and `Skip:` regex on file watcher if they're set.
=> Make back button work with tabs
