README.md
dnclient/appmeta.go
dnclient/dnclient.go
dnclient/handlers.go
dnclient/init.go
dnclient/lidarr.go
dnclient/logs.go
dnclient/tray.go
dnclient/webserver.go
examples/dnclient.conf.example
main.go

Decided on something else for the log files. Moved a few more pieces around too. Clean up.

Switch error log to http log

---

.gitignore
Makefile
go.mod
go.sum
init/bsd/freebsd.rc.d
pkg/apps/apps.go
pkg/apps/lidarr.go
pkg/apps/radarr.go
pkg/apps/readarr.go
pkg/apps/sonarr.go
pkg/client/handlers.go
pkg/client/init.go
pkg/client/tray.go
scripts/after-install.sh

This buttons up Lidarr support, among other things. Also closes #10.

Lidarr support and cleanup.

---

go.mod
go.sum
scripts/after-install.sh

This fixes a couple bugs:
- Applying tags when adding a series to Sonarr.
- Getting root folder from latest version of Readarr.
- Linux packages failing to add user. (closes #15)

Small fixes.

---

pkg/apps/radarr.go

Add get all movies endpoint for radarr to support Gaps.

---

go.mod
go.sum
pkg/apps/lidarr.go
pkg/apps/radarr.go
pkg/apps/readarr.go
pkg/apps/sonarr.go

This contribution adds the ability to get, add and delete exclusions. Also fixes already-used `id` in a few places.

Add Radarr Exclusions & other fixes

---

pkg/client/plexsnaps.go
pkg/plex/webhook.go

Adds debug for plex webhook and adds missing struct members.

Plex payload fixes

---

Makefile
README.md
examples/notifiarr.conf.example
init/docker/Dockerfile
pkg/notifiarr/notifiarr.go
pkg/snapshot/smartctl.go
pkg/snapshot/snapshot.go
pkg/ui/dlgs.go
pkg/ui/ui_other.go
pkg/ui/ui_windows.go
settings.sh

More rename pieces. Update readme, add new feature info. Add smartctl and mdadm to Docker image.. now just need to figure out how to make them work..

More Updates

---

init/docker/Dockerfile
pkg/services/checks.go
pkg/services/services.go
pkg/snapshot/raid.go
pkg/snapshot/smartctl.go
pkg/snapshot/snapshot.go
scripts/install-synology.sh

This contribution adds a Synology installation script. Also got smartctl and MegaCLI working in Docker. The Docker image is around 11MB now.

Make smartctl and megacli work in Docker + Synology install script

---

pkg/client/configfile.go
pkg/client/tray.go
pkg/services/services.go

- This adds a few new testing menus to windows and macOS. 
- Makes reload work correctly for service checks.
- Fixes the URLs for service checks (was sending to BaseURL instead of ProdURL).
- Fixes the auto-create-config-file on Synology.

Add test menus and make reload work.

---

pkg/plex/sessions.go
pkg/plex/sessions_types.go

- Adds Plex sessions structure.

Add more Plex session data.

---

examples/notifiarr.conf.example
pkg/apps/lidarr.go
pkg/apps/radarr.go
pkg/apps/readarr.go
pkg/apps/sonarr.go
pkg/client/tray.go
pkg/services/checks.go
pkg/services/services.go

Closes #35. This update adds a separate service check interval so services can be checked more often than notifiarr is updated.

Add service check intervals.

---

pkg/apps/lidarr.go
pkg/apps/readarr.go

Fix existing check when adding book.

Fix existing check when adding book.

---

.travis.yml
README.md
pkg/apps/apps.go
pkg/client/handlers.go
pkg/plex/handlers.go
pkg/plex/plex.go
pkg/plex/sessions.go

Add Plex sessions and session kill endpoints

---

examples/notifiarr.conf.example
pkg/configfile/template.go

config file template fix

---

pkg/client/handlers.go
pkg/client/update_other.go
pkg/configfile/allowedips.go
pkg/configfile/template.go
pkg/logs/cooler.go
pkg/plex/plex.go
pkg/plex/sessions.go
pkg/snapshot/synology.go

Fixing things that show up on go Report Card.

Fix minor lint problems.

---

go.mod
go.sum
pkg/client/init.go
pkg/client/start.go
pkg/snapshot/users_windows.go

Updates Starr library to fix a Sonarr bug. Disabled services when running `--cfsync`.

Fix sonarr bug, dont run services on cfsync.

---

pkg/apps/lidarr.go
pkg/apps/radarr.go
pkg/apps/readarr.go
pkg/apps/sonarr.go
pkg/client/handlers.go
pkg/client/init.go
pkg/client/start.go
pkg/client/tray.go
pkg/client/tray_commands.go
pkg/client/update_windows.go
pkg/configfile/config.go
pkg/logs/logs.go
pkg/logs/logs_windows.go
pkg/mnd/constants.go
pkg/services/services.go
pkg/snapshot/diskusage.go
pkg/snapshot/memory_linux.go
pkg/update/check.go
pkg/update/update.go
settings.sh

This fixes a problem with the Windows updater running between release and build artifact uploads.
I also created a new module to house global constants.

Bug & Lint

---

pkg/services/services.go

`x-api-key` is valid `API-Key` is not
Fixes: broken reader service check

Fix Wrong API Key Header

---

examples/notifiarr.conf.example
init/systemd/template.unit.service
pkg/client/start.go
pkg/configfile/template.go
pkg/logs/filemode.go
pkg/logs/logfiles.go
pkg/logs/logs.go

Fixes #104 by making log file mode configurable in the config file.

Add file mode

---

go.mod
go.sum
pkg/apps/apps.go
pkg/apps/lidarr.go
pkg/apps/radarr.go
pkg/apps/readarr.go
pkg/apps/sonarr.go
pkg/mnd/constants.go

This updates the starr library to bring in a sonar fix for release profiles. Also adds a starr app url check to get the correct URL on startup.

Modules update, auto url fixes.

---

pkg/client/tray.go

try to fix a bug

---

README.md
go.mod
go.sum
pkg/apps/apps.go
pkg/client/handlers.go
pkg/client/handlers_trash.go
pkg/client/handlers_version.go
pkg/client/start.go
pkg/client/webserver.go
pkg/configfile/template.go
pkg/logs/logs.go
pkg/notifiarr/cfsync.go
pkg/notifiarr/clientinfo.go
pkg/notifiarr/dashboard.go
pkg/notifiarr/gaps.go
pkg/notifiarr/handlers.go
pkg/notifiarr/handlers_plex.go
pkg/plex/info.go

- This adds missing context to some api paths.
- Fixes dashboard ordering for starr apps (recent items).
- Adds a new extra API Key input (for future integrations).
- Make trash sync skip broken updates and continue. Closes #166.
- Sends full report on trash sync update.
- Adds new trash aggregate api handler to speed up the website.
- Fixes services log file mode. Closes #165.

Fixes Aplenty

---

go.mod
go.sum
pkg/apps/sonarr.go

Add season pass API passthru for Sonarr.

---

pkg/notifiarr/dashboard.go

add plex to dashbaord

---

pkg/apps/tautulli.go

Tautulli user fix

---

pkg/apps/downloaders.go
pkg/apps/sabnzbd.go
pkg/apps/tautulli.go
pkg/bindata/files/js/common.js
pkg/bindata/files/js/golists.js
pkg/bindata/files/js/navigation.js
pkg/bindata/files/js/services.js
pkg/bindata/templates/downloaders/deluge.html
pkg/bindata/templates/downloaders/nzbget.html
pkg/bindata/templates/downloaders/qbit.html
pkg/bindata/templates/downloaders/rtorrent.html
pkg/bindata/templates/downloaders/sabnzbd.html
pkg/bindata/templates/media/plex.html
pkg/bindata/templates/media/tautulli.html
pkg/bindata/templates/services.html
pkg/bindata/templates/starr/lidarr.html
pkg/bindata/templates/starr/prowlarr.html
pkg/bindata/templates/starr/radarr.html
pkg/bindata/templates/starr/readarr.html
pkg/bindata/templates/starr/sonarr.html
pkg/configfile/template.go
pkg/plex/plex.go
pkg/services/apps.go
pkg/services/checks.go
pkg/services/config.go

This adds optional SSL verification to all URL inputs.
TODO: 
- make app service checks do ssl checks
- update addInstacne js method.

Verify SSL

---

.golangci.yml
go.mod
go.sum
pkg/bindata/templates/index.html
pkg/client/instance_tests.go
pkg/services/services.go
pkg/snapshot/diskusage.go

Closes #265 by adding a flashy thing when there are unsaved changes.
Closes #261 by sending service states to website before shut down.
Closes #254 because that problem is on the website.

A few fixes.

---

.gitignore
pkg/bindata/templates/config.html
pkg/client/init.go
pkg/configfile/config.go
pkg/configfile/template.go
pkg/website/server.go
pkg/website/website_routes.go

Remove mode

---

pkg/apps/apps.go
pkg/apps/downloaders.go
pkg/apps/lidarr.go
pkg/apps/prowlarr.go
pkg/apps/radarr.go
pkg/apps/readarr.go
pkg/apps/sabnzbd.go
pkg/apps/sonarr.go
pkg/apps/tautulli.go
pkg/bindata/templates/config.html
pkg/bindata/templates/downloaders/deluge.html
pkg/bindata/templates/downloaders/nzbget.html
pkg/bindata/templates/downloaders/qbit.html
pkg/bindata/templates/downloaders/rtorrent.html
pkg/bindata/templates/downloaders/sabnzbd.html
pkg/bindata/templates/media/plex.html
pkg/bindata/templates/media/tautulli.html
pkg/bindata/templates/snapshot/mysql.html
pkg/bindata/templates/starr/lidarr.html
pkg/bindata/templates/starr/prowlarr.html
pkg/bindata/templates/starr/radarr.html
pkg/bindata/templates/starr/readarr.html
pkg/bindata/templates/starr/sonarr.html
pkg/client/instance_tests.go
pkg/configfile/config.go

This fixes a few UI bugs. It also fixes setting 'No Timeout' on an instance (it wouldn't work before).

UI and 'No Timeout' fixes.

---

pkg/bindata/templates/includes/filetablelist.html
pkg/bindata/templates/monitoring.html
pkg/bindata/templates/system.html
pkg/client/html_templates.go
pkg/configfile/config.go
pkg/website/clientinfo.go
pkg/website/phpdate.go

Adds date format from website configuration.

Add date format

---

go.mod
go.sum
pkg/apps/apps.go
pkg/apps/lidarr.go
pkg/apps/prowlarr.go
pkg/apps/radarr.go
pkg/apps/readarr.go
pkg/apps/sonarr.go
pkg/bindata/templates/triggers.html
pkg/client/handlers_trash.go
pkg/client/tray.go
pkg/triggers/backups/corruption.go
pkg/triggers/cfsync/common.go
pkg/triggers/cfsync/handler.go
pkg/triggers/cfsync/radarr.go
pkg/triggers/cfsync/sonarr.go

This contribution adds quality definition endpoints and custom format endpoints for sonarr.
Closes #295. Requires https://github.com/golift/starr/pull/57

Custom Format / TRaSH updates

---

pkg/bindata/files/js/golists.js
pkg/bindata/files/js/triggers.js
pkg/bindata/templates/ajax/cmdargs.html
pkg/bindata/templates/ajax/cmdstats.html
pkg/bindata/templates/commands.html
pkg/client/handlers.go
pkg/client/handlers_gui.go
pkg/client/instance_tests.go
pkg/client/start.go
pkg/client/tray.go
pkg/configfile/template.go
pkg/services/interface.go
pkg/services/services.go
pkg/triggers/commands/builder.go
pkg/triggers/commands/command.go
pkg/triggers/commands/setup.go
pkg/triggers/common/triggers.go
unstable

Fixes a few bugs with service checks introduced by #337. Adds usable command arguments and closes #304.

Command Arguments

---

pkg/bindata/docs/api_docs.go
pkg/bindata/templates/landing.html
pkg/triggers/backups/corruption.go
pkg/triggers/emptytrash/plex.go
pkg/triggers/handler.go
pkg/triggers/triggers.go
unstable

Empty Trash Trigger

---

go.mod
go.sum
pkg/apps/radarr.go
pkg/apps/sonarr.go
pkg/bindata/docs/api_docs.go
pkg/snapshot/snapshot.go
pkg/snapshot/system.go
pkg/snapshot/temperatures.go

- Closes #348 by removing cpu/mem error for PIDs (mostly a macOS problem).
- Closes #345 by adding media management naming endpoints to sonarr and radarr.

Remove some snapshot errors, add naming endpoints.

---

README.md
go.mod
go.sum
pkg/bindata/files/js/services.js
pkg/bindata/templates/services.html
pkg/client/html_templates.go
pkg/client/instance_tests.go
pkg/services/check_ping.go
pkg/services/checks.go
pkg/services/config.go

Ping service check

---

pkg/client/init.go
pkg/triggers/starrqueue/downloads.go

More fixes to make downloading items tracking work. Re: Notifiarr/website#227

fix downloading items

---

pkg/bindata/templates/triggers.html
pkg/triggers/backups/backups.go
pkg/triggers/backups/config.go
pkg/triggers/backups/corruption.go
pkg/triggers/cfsync/radarr.go
pkg/triggers/cfsync/sonarr.go

Fixes the app the second instance of sonarr or radarr actually get their customized TRaSH profiles sync'd. 
- Closes #375.
- Closes #376 by fixing the sync messages.

fix second instance trash sync + more

---

.github/workflows/codetests.yml
.travis.yml
Makefile
init/buildinfo.sh
init/docker/hooks/build
scripts/notarize.sh

- Add script to customize released macOS dmg file.
- Simplify Makefile some.
- Make GH Actions test more things, including `make release`.
- Make Travis CI do less.

Dn2 build better

---

userscripts/install-synology.sh
userscripts/install.sh

Make synology install script work with dsm7. Closes #372.

make syno script work with dsm7

---

pkg/client/html_templates.go

Update unit names

---

.gitignore
Makefile
pkg/bindata/templates/index.html
pkg/bindata/templates/profile.html
pkg/bindata/templates/triggers.html

- Closes #435.
- Adds 6 more ignorable headers for trust profile.
- Adds a WebUI trigger for MDB List.

Build example config file before packaging.

---

pkg/bindata/templates/profile.html

add more ignored auth headers

---

init/docker/Dockerfile
pkg/client/handlers.go

Allow any plex session id

---

pkg/bindata/templates/profile.html
pkg/client/handlers_plex.go

Fixes #538 
Fixup! to https://github.com/Notifiarr/notifiarr/commit/da84b59289adadac4bf920c80219487362f55370
Adds
media.scrobble – Media is viewed (played past the 90% mark).

fix(plex) scrobble typo

---

pkg/client/handlers_plex.go

Reverts Notifiarr/notifiarr#540

Revert "fix(plex) scrobble typo"

---

pkg/configfile/password.go

Remove slash from generated passwords.

---

pkg/client/start.go
pkg/services/config.go

Introduced a bug that disabled all snapshots. This turns them back on.

Fix missing snapshots

---

.github/workflows/codetests.yml
pkg/bindata/templates/profile.html

- sort headers alphabetically
- add requested auth headers
- add auth headers suggested by chatgpt
Fixes #598

Hide more auth headers

---

pkg/apps/integrations.go
pkg/bindata/templates/media/plex.html
pkg/bindata/templates/media/tautulli.html

Remove no timeout for plex

---

pkg/client/tray.go
pkg/services/services.go

Fix service count toast

---

pkg/apps/lidarr.go
pkg/apps/prowlarr.go
pkg/apps/radarr.go
pkg/apps/readarr.go
pkg/apps/setup.go
pkg/apps/sonarr.go

return starr app code

---

pkg/bindata/templates/triggers.html
pkg/triggers/cfsync/radarr.go
pkg/triggers/cfsync/sonarr.go
pkg/triggers/handler.go

cleanup sync naming

---

pkg/apps/integrations.go
pkg/website/website.go

Adds hostname and other data to file uploads. Fixes bug in tautulli that makes the save button appear without changes.

add hostname to file uploads

---

pkg/snapshot/mysql.go

Update mysql.go for lint 

---

pkg/triggers/data/store.go
pkg/triggers/starrqueue/downloads.go
pkg/triggers/starrqueue/setup.go
pkg/triggers/starrqueue/stuckitems.go

add more meta to active downloads

---

pkg/configfile/template.go

protect quotes everywhere

---

pkg/client/tunnel.go
pkg/client/webserver.go
pkg/configfile/helper.go
pkg/logs/logs_windows.go
pkg/website/clientinfo/clientinfo.go

No real logic changes. Just moves tunnel code from web server file to tunnel file.

Re-arrange tunnel

---

Makefile
go.mod
go.sum
main.go
pkg/bindata/templates/tunnel.html
pkg/client/tray.go
pkg/client/tunnel.go
pkg/logs/logs.go
pkg/ui/ui_darwin.go
pkg/ui/ui_other.go
pkg/ui/ui_windows.go
pkg/website/clientinfo/clientinfo.go

- Removes the console window on Windows (.exe).
- Closes #719 
- Adds previous tunnel info to tunnel update payload sent to website.
- Adds tunnels' locations to Tunnel UI page.

Remove Windows console window

---

pkg/logs/logfiles.go
pkg/logs/logs.go

Set log files when folder provided.

---

.github/workflows/release.yml
pkg/bindata/templates/config.html
pkg/client/client_windows.go
pkg/client/tray.go
pkg/client/tray_commands.go
pkg/configfile/config.go
pkg/configfile/template.go
pkg/mnd/variables.go
pkg/update/check.go
pkg/update/unstable.go

- Adds code to update from unstable website.
- Closes #684

Mac/win: Update from unstable website.

---

go.mod
go.sum
pkg/apps/apppkg/sabnzbd/sabnzbd.go
pkg/client/client_windows.go

- Fixes a bug in SAB dashboard: https://github.com/sabnzbd/sabnzbd/issues/2911
- Closes #272 (by updating gopsutil lib).

SAB bug fix and return the macOS/ARM temps.

---

.github/workflows/ghcr.yml
.github/workflows/release.yml
init/docker/hooks/build

Makes it easier to identify which built made a version.

add version to step names

---

pkg/triggers/crontimer/custom.go
pkg/website/server.go

upcheck payload wasn't json, fix it.

fix upcheck

---

pkg/bindata/templates/downloaders/deluge.html
pkg/bindata/templates/downloaders/nzbget.html
pkg/bindata/templates/downloaders/qbit.html
pkg/bindata/templates/downloaders/rtorrent.html
pkg/bindata/templates/downloaders/sabnzbd.html
pkg/bindata/templates/downloaders/transmission.html
pkg/bindata/templates/filewatcher.html
pkg/bindata/templates/includes/filetablelist.html
pkg/bindata/templates/index.html
pkg/bindata/templates/logfiles.html
pkg/bindata/templates/media/plex.html
pkg/bindata/templates/media/tautulli.html
pkg/bindata/templates/profile.html
pkg/bindata/templates/services.html
pkg/bindata/templates/snapshot/mysql.html
pkg/bindata/templates/snapshot/nvidia.html
pkg/bindata/templates/starr/lidarr.html
pkg/bindata/templates/starr/prowlarr.html
pkg/bindata/templates/starr/radarr.html
pkg/bindata/templates/starr/readarr.html
pkg/bindata/templates/starr/sonarr.html
pkg/bindata/templates/triggers.html

No logic changes, just new lines.

Shorten a bunch of html lines.

---

pkg/apps/radarr.go
pkg/apps/sonarr.go

This will add the endpoints to the client for import lists. The starr library looks like it already has everything
TODO

Sonarr list endpoints

---

pkg/triggers/cfsync/lidarr.go
pkg/triggers/cfsync/radarr.go
pkg/triggers/cfsync/sonarr.go

info lines instead of debug

---

pkg/triggers/dashboard/dashboard.go
pkg/triggers/dashboard/deluge.go
pkg/triggers/dashboard/lidarr.go
pkg/triggers/dashboard/nzbget.go
pkg/triggers/dashboard/qbit.go
pkg/triggers/dashboard/radarr.go
pkg/triggers/dashboard/readarr.go
pkg/triggers/dashboard/rtorrent.go
pkg/triggers/dashboard/sabnzb.go
pkg/triggers/dashboard/sonarr.go
pkg/triggers/dashboard/transmission.go
pkg/website/clientinfo/clientinfo.go

allow website to disable dashboarding specific apps

---

.github/workflows/release.yml
.gitignore
Makefile
init/windows/signexe.sh

Sign 'em if ya got 'em.
- Closes #748

Sign windows exe.

---

pkg/bindata/files/js/services.js
pkg/bindata/templates/services.html

allow service timeout to be 6m

---

.github/workflows/codetests.yml
Makefile
frontend/src/Index.svelte
frontend/src/Landing.svelte
frontend/src/Navigation.svelte
frontend/src/app.css
frontend/src/commands/Index.svelte
frontend/src/configuration/Index.svelte
frontend/src/downloadApps/Index.svelte
frontend/src/endpoints/Index.svelte
frontend/src/fileWatcher/Index.svelte
frontend/src/integrations/Index.svelte
frontend/src/lib/login.ts
frontend/src/lib/util.ts
frontend/src/logFiles/Index.svelte
frontend/src/mediaApps/Index.svelte
frontend/src/metrics/Index.svelte
frontend/src/monitoring/Index.svelte
frontend/src/profile/Index.svelte
frontend/src/serviceChecks/Index.svelte
frontend/src/siteTunnel/Index.svelte
frontend/src/snapshotApps/Index.svelte
frontend/src/starrApps/Index.svelte
frontend/src/system/Index.svelte
frontend/src/triggers/Index.svelte
pkg/client/handlers_gui.go

- Setup a responsive nav page that works well on mobile.
- Fixes the background so it stretches and fills.
- Adds a bunch of placeholder files for each component.
- Adds the username to the http.Request object context (so it can be used during the login request).
- Returns the Profile structure on login (so we can use the feature here ^ and avoid one additional http request).

Add navigation page to new UI

---

pkg/apps/apppkg/sabnzbd/sabnzbd.go
pkg/apps/apppkg/tautulli/tautulli.go
pkg/apps/integrations.go

Data conversions are not working as well as they could. This fixes them.

Fix some json tags

---

frontend/src/includes/locale/nl.json

Currently translated at 65.2% (615 of 943 strings)
Translation: Client/Frontend
Translate-URL: https://translate.notifiarr.com/projects/client/frontend/nl/

Translated using Weblate (Dutch)

---

frontend/src/api/profile.svelte.ts
frontend/src/pages/configuration/Index.svelte
frontend/src/pages/configuration/Logging.svelte
frontend/src/pages/configuration/Network.svelte
frontend/src/pages/configuration/SSLConfig.svelte
frontend/src/pages/configuration/Services.svelte
frontend/src/pages/configuration/System.svelte
pkg/website/website.go

- Splits the main config page into a bunch of sub components.
- Makes changes on the config page highlight.
- Makes the save button only work when something changes.
- Re-arranges the website shutdown code to make it more reliable.

Config page fixes

---

frontend/src/api/fetch.ts
frontend/src/includes/locale/locale.svelte.ts
frontend/src/index.ts
frontend/src/navigation/ProfileMenu.svelte
frontend/vite.config.ts
pkg/services/apps.go
pkg/services/checks.go
pkg/services/config.go
pkg/services/services.go

- Logs for service checks were not going to the services log file. Fixed here.
- Also added some vite options to code-split the app.
- Renamed index.ts to locale.ts

Bug fix: service log file works now
